export const enum ConversationEnum {
  CONVERSATION_CREATED = "CONVERSATION_CREATED",
  CONVERSATION_UPDATED = "CONVERSATION_UPDATED",
}

export const enum MessageEnum {
  MESSAGE_SENT = "MESSAGE_SENT",
}

export const enum UserEnum {
  USER_INVITED_TO_CONVERSATION = "USER_INVITED_TO_CONVERSATION",
}
